<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>GlyphEcho</AssemblyName>
    <RootNamespace>GlyphEcho</RootNamespace>
    <Version>0.2.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="GlyphEcho.Updater\**\*.cs" />
    <None Remove="GlyphEcho.Updater\**\*" />
  </ItemGroup>
</Project>
