using System.Windows;
using System.Windows.Controls;
using WpfControl = System.Windows.Controls.Control;
using WpfButton = System.Windows.Controls.Button;
using WpfCheckBox = System.Windows.Controls.CheckBox;
using WpfRadioButton = System.Windows.Controls.RadioButton;
using WpfComboBox = System.Windows.Controls.ComboBox;
using Forms = System.Windows.Forms;
using MediaColor = System.Windows.Media.Color;
using MediaColorConverter = System.Windows.Media.ColorConverter;
using SolidColorBrush = System.Windows.Media.SolidColorBrush;

namespace GlyphEcho;
public partial class MainWindow : Window
{
    public MainWindow() { InitializeComponent(); Closing += OnClosing; Load(); }
    private void Navigate_Click(object sender, RoutedEventArgs e) { var tag = (sender as FrameworkElement)?.Tag?.ToString(); CatalogPanel.Visibility = tag == "Keys" ? Visibility.Visible : Visibility.Collapsed; if (tag == "Keys") { DefaultPanel.Visibility = Visibility.Collapsed; RulesPanel.Visibility = Visibility.Collapsed; RefreshCatalog(); return; } DefaultPanel.Visibility = Visibility.Visible; RulesPanel.Visibility = Visibility.Visible; if (tag == "Rules") { Grid.SetColumn(RulesPanel, 0); Grid.SetColumnSpan(RulesPanel, 3); } else { Grid.SetColumn(RulesPanel, 2); Grid.SetColumnSpan(RulesPanel, 1); } }
    private void Load() { var s = App.Settings; DefaultEnabled.IsChecked = s.DefaultRule.Enabled; DefaultSingle.IsChecked = s.DefaultRule.ShowSingleKeys; CatalogDefaultEnabled.IsChecked = s.NewKeysEnabled; ModeSelect.SelectedIndex = s.Mode switch { "游戏模式" => 1, "演示模式" => 2, _ => 0 }; CloseBehavior.SelectedIndex = s.CloseToTray ? 0 : 1; ThemeSelect.SelectedIndex = s.Theme switch { "深色" => 1, "跟随系统" => 2, _ => 0 }; PositionSelect.SelectedItem = PositionSelect.Items.OfType<ComboBoxItem>().FirstOrDefault(x => (string)x.Content == s.OverlayPosition) ?? PositionSelect.Items[0]; RefreshMonitors(); (s.DefaultRule.Level switch { 1 => Low, 3 => High, _ => Medium }).IsChecked = true; RulesList.ItemsSource = s.Rules; RefreshCatalog(); UpdateRuleButtons(); ApplyTheme(); }
    private void Save_Click(object sender, RoutedEventArgs e) { App.Settings.DefaultRule.Enabled = DefaultEnabled.IsChecked == true; App.Settings.DefaultRule.ShowSingleKeys = DefaultSingle.IsChecked == true; App.Settings.Mode = (ModeSelect.SelectedItem as ComboBoxItem)?.Content?.ToString() ?? "普通模式"; App.Settings.CloseToTray = CloseBehavior.SelectedIndex != 1; App.Settings.Theme = (ThemeSelect.SelectedItem as ComboBoxItem)?.Content?.ToString() ?? "浅色"; App.Settings.MonitorIndex = Math.Max(0, MonitorSelect.SelectedIndex); App.Settings.OverlayPosition = (PositionSelect.SelectedItem as ComboBoxItem)?.Content?.ToString() ?? "右下"; App.Settings.DefaultRule.Level = High.IsChecked == true ? 3 : Low.IsChecked == true ? 1 : 2; ApplyTheme(); App.SaveSettings(); App.Overlay?.RefreshPosition(); System.Windows.MessageBox.Show("设置已保存，展示会立即使用新规则。", "GlyphEcho", MessageBoxButton.OK, MessageBoxImage.Information); }
    private void OnClosing(object? sender, System.ComponentModel.CancelEventArgs e) { var closeToTray = CloseBehavior.SelectedIndex != 1; App.Settings.CloseToTray = closeToTray; App.SaveSettings(); if (closeToTray && !App.IsShuttingDown) { e.Cancel = true; Hide(); return; } if (!App.IsShuttingDown) { e.Cancel = true; App.ExitApplication(); } }
    private void AddRule_Click(object sender, RoutedEventArgs e) { var rule = new DisplayRule { Name = "新应用规则", Process = KeyboardHook.GetForegroundProcessName(), ProcessPath = KeyboardHook.GetForegroundProcessPath(), Level = App.Settings.DefaultRule.Level, Enabled = true, UseGlobalCatalog = true }; var editor = new RuleEditorWindow(rule, false, App.Settings.GlobalKeyCatalog) { Owner = this }; if (editor.ShowDialog() == true) { App.Settings.Rules.Add(rule); RefreshRules(); RulesList.SelectedItem = rule; App.SaveSettings(); } }
    private void DuplicateRule_Click(object sender, RoutedEventArgs e) { if (RulesList.SelectedItem is not DisplayRule source) return; var copy = source.Clone(); copy.Priority = source.Priority + 1; App.Settings.Rules.Add(copy); RefreshRules(); RulesList.SelectedItem = copy; App.SaveSettings(); }
    private void Preview_Click(object sender, RoutedEventArgs e) { App.Overlay?.Present("Ctrl + C", "预览", App.Settings.DefaultRule); }
    private void CatalogSearch_TextChanged(object sender, TextChangedEventArgs e) => RefreshCatalog();
    private void CatalogDefaultEnabled_Changed(object sender, RoutedEventArgs e) { if (CatalogDefaultEnabled is null) return; App.Settings.NewKeysEnabled = CatalogDefaultEnabled.IsChecked == true; App.SaveSettings(); }
    internal void RefreshCatalog() { if (CatalogList is null) return; var query = CatalogSearchBox?.Text?.Trim() ?? ""; CatalogList.ItemsSource = App.Settings.GlobalKeyCatalog.Where(x => query.Length == 0 || x.Key.Contains(query, StringComparison.OrdinalIgnoreCase) || x.Description.Contains(query, StringComparison.OrdinalIgnoreCase)).OrderByDescending(x => x.CreatedAt).ThenBy(x => x.Key, StringComparer.OrdinalIgnoreCase).ToList(); }
    private void DeleteCatalogKey_Click(object sender, RoutedEventArgs e) { if ((sender as FrameworkElement)?.DataContext is not KeyRule key) return; App.Settings.GlobalKeyCatalog.Remove(key); var normalized = KeyboardHook.NormalizeForRule(key.Key); if (!App.Settings.IgnoredKeys.Any(x => KeyboardHook.NormalizeForRule(x).Equals(normalized, StringComparison.OrdinalIgnoreCase))) App.Settings.IgnoredKeys.Add(key.Key); App.Settings.DefaultRule.KeyRules = [.. App.Settings.GlobalKeyCatalog.Select(x => x.Clone())]; RefreshCatalog(); App.SaveSettings(); }
    private void EditRule_Click(object sender, RoutedEventArgs e) { if (RulesList.SelectedItem is not DisplayRule rule) { System.Windows.MessageBox.Show("请先选择一条应用规则。", "GlyphEcho", MessageBoxButton.OK, MessageBoxImage.Information); return; } var editor = new RuleEditorWindow(rule, false, App.Settings.GlobalKeyCatalog) { Owner = this }; if (editor.ShowDialog() == true) { RefreshRules(); App.SaveSettings(); } }
    private void DeleteRule_Click(object sender, RoutedEventArgs e) { if (RulesList.SelectedItem is not DisplayRule rule) return; if (System.Windows.MessageBox.Show($"删除规则“{rule.Name}”？", "确认删除", MessageBoxButton.YesNo, MessageBoxImage.Warning) != MessageBoxResult.Yes) return; App.Settings.Rules.Remove(rule); RefreshRules(); App.SaveSettings(); }
    private void RefreshRules() { RulesList.ItemsSource = null; RulesList.ItemsSource = App.Settings.Rules; UpdateRuleButtons(); }
    private void RulesList_SelectionChanged(object sender, SelectionChangedEventArgs e) { UpdateRuleButtons(); }
    internal void RefreshMonitors() { var previous = App.Settings.MonitorIndex; MonitorSelect.Items.Clear(); foreach (var screen in Forms.Screen.AllScreens) MonitorSelect.Items.Add(screen.Primary ? "屏幕 1（主屏）" : $"屏幕 {MonitorSelect.Items.Count + 1}"); App.Settings.MonitorIndex = Math.Clamp(previous, 0, Math.Max(0, MonitorSelect.Items.Count - 1)); MonitorSelect.SelectedIndex = App.Settings.MonitorIndex; App.Overlay?.RefreshPosition(); }
    private void UpdateRuleButtons() { var hasSelection = RulesList?.SelectedItem is DisplayRule; if (EditRuleButton != null) EditRuleButton.IsEnabled = hasSelection; if (DeleteRuleButton != null) DeleteRuleButton.IsEnabled = hasSelection; if (DuplicateRuleButton != null) DuplicateRuleButton.IsEnabled = hasSelection; }
    internal void UpdateListenerStatus(bool running) { var text = running ? "监听中" : "监听失败"; if (ListenerStatusText != null) ListenerStatusText.Text = text; if (SidebarStatusText != null) SidebarStatusText.Text = running ? "后台监听已启用" : "后台监听未启动"; }
    private void ApplyTheme() { var dark = ThemeSelect?.SelectedIndex == 1; Background = new SolidColorBrush((MediaColor)MediaColorConverter.ConvertFromString(dark ? "#182321" : "#F3F6F5")); DefaultPanel.Background = new SolidColorBrush((MediaColor)MediaColorConverter.ConvertFromString(dark ? "#24322F" : "#FFFFFF")); RulesPanel.Background = DefaultPanel.Background; ApplyThemeTree(DefaultPanel, dark); ApplyThemeTree(RulesPanel, dark); }
    private static void ApplyThemeTree(DependencyObject root, bool dark) { foreach (var child in LogicalTreeHelper.GetChildren(root).OfType<DependencyObject>()) { if (child is TextBlock or WpfCheckBox or WpfRadioButton or WpfComboBox) { if (child is WpfControl control) control.Foreground = dark ? System.Windows.Media.Brushes.White : System.Windows.Media.Brushes.Black; else if (child is TextBlock text) text.Foreground = dark ? System.Windows.Media.Brushes.White : System.Windows.Media.Brushes.Black; } if (child is WpfControl c && c is not WpfButton) c.Background = dark ? new SolidColorBrush((MediaColor)MediaColorConverter.ConvertFromString("#30413D")) : null; ApplyThemeTree(child, dark); } }
}
